version: "3.9"

services:
  vscode:
    image: maskrcnn-vscode:glibc235
    container_name: maskrcnn-vscode-dev

    tty: true
    stdin_open: true
    hostname: Container
    shm_size: 80GB

    environment:
      - TZ=Asia/Seoul
      - PYTHONDONTWRITEBYTECODE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    devices:
      - nvidia.com/gpu=all

    volumes:
      - ${HOME}/.vscode-server:/root/.vscode-server
      - ${HOME}/.vscode-cli:/root/.vscode-cli
      - ${HOME}/.vscode-tunnels:/root/.vscode-tunnels

      - ${PWD}:/workspace
      - /mnt/nas100/forGPU/SCH_project/seungsu0806/data:/workspace/data

    working_dir: /workspace
    entrypoint: /workspace/entrypoint.sh
